### ISSUE TITLE
calculate_kspace_PP error with EPI sequence

### ISSUE THREAD

**Issue by magdamd** [imr-framework/pypulseq#192] opened 2024-08-20 15:01 UTC
**Bug**

Currently using pypulseq 1.4.0 and when reading an EPI sequence and then trying to use the calculate_kspacePP, the following error is returned:

"    
if ii_next_excitation > 0 and i_excitation[ii_next_excitation] == i_period:

IndexError: index 1 is out of bounds for axis 0 with size 1
"

**To Reproduce**

I attach the seq file to this issue ([EPI_PE1_time05x_64.txt](https://github.com/user-attachments/files/16677653/EPI_PE1_time05x_64.txt)).

The code needed is the following:

```
import pypulseq as pp

file_name = r"EPI_PE1_time05x_64.txt"

seq = pp.Sequence()
seq.read(file_name)

ktraj, _, _, _, _ = seq.calculate_kspacePP()
```

**Comment by btasdelen** [comment] 2024-08-23 21:42
Hi @magdamd. Unable to reproduce the error with PyPulseq 1.4.2 from pip. 1.4.0 is quite old, has some incomplete functions, and has a lot of bugs, please upgrade to 1.4.2.

Also, `seq.calculate_kspacePP()` is deprecated, and calls `calculate_kspace` under the hood, you can directly use `seq.calculate_kspace()` function.

**Comment by btasdelen** [comment] 2024-08-23 21:42
Closing, please feel free to re-open the issue if upgrading the package does not solve the issue.

**Closed by btasdelen** 2024-08-23 21:42 UTC
